# Generated by Django 5.2.17 on 2026-08-26 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'etiket',
                'verbose_name_plural': 'etiketler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('sira', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ilçe',
                'verbose_name_plural': 'ilçeler',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Yonlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_yol', models.CharField(db_index=True, max_length=400, unique=True)),
                ('yeni_yol', models.CharField(max_length=400)),
                ('kod', models.PositiveSmallIntegerField(default=301)),
                ('sebep', models.CharField(blank=True, max_length=200)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'yönlendirme',
                'verbose_name_plural': 'yönlendirmeler',
                'ordering': ['eski_yol'],
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=80, unique=True)),
                ('sira', models.PositiveSmallIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
                ('ust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='altlar', to='taksonomi.kategori')),
            ],
            options={
                'verbose_name': 'kategori',
                'verbose_name_plural': 'kategoriler',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Kaynak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, unique=True)),
                ('tur', models.CharField(choices=[('ajans', 'Ajans'), ('dis_yayin', 'Dış yayın')], default='dis_yayin', max_length=12)),
                ('aktif', models.BooleanField(default=True)),
                ('birlesti_ile', models.ForeignKey(blank=True, help_text='Tekrar eden kayıt buraya bağlanır; bağlantı kaybolmaz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birlesenler', to='taksonomi.kaynak')),
            ],
            options={
                'verbose_name': 'kaynak',
                'verbose_name_plural': 'kaynaklar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='KategoriTur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('haber', 'Haber'), ('foto', 'Foto galeri'), ('video', 'Video')], max_length=8)),
                ('eski_id', models.PositiveIntegerField(help_text='Eski sistemdeki kategori kimliği. Foto/video adresinde geçer.')),
                ('slug', models.SlugField(help_text='DONDURULMUŞ. Adresin parçası; değiştirmek eski bağlantıları kırar.', max_length=80)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turler', to='taksonomi.kategori')),
            ],
            options={
                'verbose_name': 'kategori türü',
                'verbose_name_plural': 'kategori türleri',
                'ordering': ['kategori__sira', 'tur'],
                'constraints': [models.UniqueConstraint(fields=('tur', 'slug'), name='tur_slug_tekil'), models.UniqueConstraint(fields=('tur', 'eski_id'), name='tur_eskiid_tekil'), models.UniqueConstraint(fields=('kategori', 'tur'), name='kategori_tur_tekil')],
            },
        ),
    ]
