# Generated by Django 5.2.17 on 2026-08-27 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taksonomi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigIntegerField(editable=False, help_text='Eski sistemdeki yazar kimliği. Adresin parçası.', primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, help_text='DONDURULMUŞ. Eski adresten çıkarıldı.', max_length=120)),
                ('ad', models.CharField(max_length=120)),
                ('unvan', models.CharField(blank=True, max_length=120)),
                ('ozgecmis', models.TextField(blank=True)),
                ('eposta', models.EmailField(blank=True, max_length=254)),
                ('aktif', models.BooleanField(default=True, help_text='Yalnız LİSTELERİ süzer. Pasif yazarın sayfası yine açılır; eski bağlantılar 404 olmamalı.')),
                ('sira', models.PositiveSmallIntegerField(default=0)),
                ('sayfasi_tarandi', models.BooleanField(default=False, help_text='Yazar sayfası arşivden alındı mı. Yanlışsa kayıt köşe yazısından türetilmiş geçici kayıttır.')),
                ('gorsel_url', models.URLField(blank=True, max_length=600)),
                ('gorsel_var', models.BooleanField(default=False)),
                ('gorsel_dosya', models.CharField(blank=True, max_length=300)),
                ('eski_url', models.URLField(blank=True, max_length=600)),
            ],
            options={
                'verbose_name': 'yazar',
                'verbose_name_plural': 'yazarlar',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='FotoGaleri',
            fields=[
                ('id', models.BigIntegerField(editable=False, help_text='Eski sistemdeki kimlik. Adresin parçası; değiştirilemez.', primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, help_text='DONDURULMUŞ. Eski adresten çıkarıldı, başlıktan üretilmedi.', max_length=220)),
                ('baslik', models.CharField(max_length=300)),
                ('spot', models.TextField(blank=True)),
                ('durum', models.PositiveSmallIntegerField(choices=[(1, 'Aktif'), (2, 'Pasif'), (3, 'Silinmiş'), (4, 'Arşiv')], default=1)),
                ('yayin_zamani', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guncelleme_zamani', models.DateTimeField(blank=True, null=True)),
                ('gorsel_url', models.URLField(blank=True, help_text='Kaynaktaki adres. Yalnız izdir; sayfa uzağa bağlanmaz.', max_length=600)),
                ('gorsel_alt', models.CharField(blank=True, max_length=300)),
                ('gorsel_var', models.BooleanField(default=False, help_text='Yerelde dosya var mı.')),
                ('gorsel_dosya', models.CharField(blank=True, help_text='ARŞİV KÖKÜNE göreli yol, ör. gorseller-galeri/2021-02/x.webp.', max_length=300)),
                ('eski_url', models.URLField(blank=True, max_length=600)),
                ('goc_guveni', models.CharField(blank=True, max_length=12)),
                ('kategori_dilimi', models.CharField(help_text='Adresteki `{slug}-{katid}` parçası, kaynaktan BİREBİR. Taksonomi tanımayan dilimler (ör. haber-213) buradan yaşar.', max_length=120)),
                ('kareler_eksik', models.BooleanField(default=True, help_text='Kareler kaynaktan alınamadıysa doğru. Sayfa bunu okura söyler.')),
                ('kareler_notu', models.CharField(blank=True, max_length=300)),
                ('kategori', models.ForeignKey(blank=True, help_text='Taksonomide karşılığı yoksa boş kalır; adres yine çalışır.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taksonomi.kategori')),
            ],
            options={
                'verbose_name': 'foto galeri',
                'verbose_name_plural': 'foto galeriler',
                'ordering': ['-yayin_zamani'],
            },
        ),
        migrations.CreateModel(
            name='GaleriKaresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveSmallIntegerField(default=0)),
                ('dosya', models.CharField(help_text='Arşiv köküne göreli yol.', max_length=300)),
                ('alt', models.CharField(blank=True, max_length=300)),
                ('aciklama', models.TextField(blank=True)),
                ('galeri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kareler', to='medya.fotogaleri')),
            ],
            options={
                'verbose_name': 'galeri karesi',
                'verbose_name_plural': 'galeri kareleri',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigIntegerField(editable=False, help_text='Eski sistemdeki kimlik. Adresin parçası; değiştirilemez.', primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, help_text='DONDURULMUŞ. Eski adresten çıkarıldı, başlıktan üretilmedi.', max_length=220)),
                ('baslik', models.CharField(max_length=300)),
                ('spot', models.TextField(blank=True)),
                ('durum', models.PositiveSmallIntegerField(choices=[(1, 'Aktif'), (2, 'Pasif'), (3, 'Silinmiş'), (4, 'Arşiv')], default=1)),
                ('yayin_zamani', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guncelleme_zamani', models.DateTimeField(blank=True, null=True)),
                ('gorsel_url', models.URLField(blank=True, help_text='Kaynaktaki adres. Yalnız izdir; sayfa uzağa bağlanmaz.', max_length=600)),
                ('gorsel_alt', models.CharField(blank=True, max_length=300)),
                ('gorsel_var', models.BooleanField(default=False, help_text='Yerelde dosya var mı.')),
                ('gorsel_dosya', models.CharField(blank=True, help_text='ARŞİV KÖKÜNE göreli yol, ör. gorseller-galeri/2021-02/x.webp.', max_length=300)),
                ('eski_url', models.URLField(blank=True, max_length=600)),
                ('goc_guveni', models.CharField(blank=True, max_length=12)),
                ('kategori_dilimi', models.CharField(help_text='Adresteki `{slug}-{katid}` parçası, kaynaktan BİREBİR. Taksonomi tanımayan dilimler (ör. haber-213) buradan yaşar.', max_length=120)),
                ('video_url', models.URLField(blank=True, max_length=600)),
                ('gomulu_url', models.URLField(blank=True, max_length=600)),
                ('sure', models.CharField(blank=True, help_text='Kaynaktaki hâli (ISO 8601, ör. PT2M30S). İz olarak durur.', max_length=40)),
                ('sure_saniye', models.PositiveIntegerField(default=0, help_text='Gösterim ve sıralama için çözülmüş hâli.')),
                ('kategori', models.ForeignKey(blank=True, help_text='Taksonomide karşılığı yoksa boş kalır; adres yine çalışır.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taksonomi.kategori')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videolar',
                'ordering': ['-yayin_zamani'],
            },
        ),
        migrations.CreateModel(
            name='KoseYazisi',
            fields=[
                ('id', models.BigIntegerField(editable=False, help_text='Eski sistemdeki kimlik. Adresin parçası; değiştirilemez.', primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, help_text='DONDURULMUŞ. Eski adresten çıkarıldı, başlıktan üretilmedi.', max_length=220)),
                ('baslik', models.CharField(max_length=300)),
                ('spot', models.TextField(blank=True)),
                ('durum', models.PositiveSmallIntegerField(choices=[(1, 'Aktif'), (2, 'Pasif'), (3, 'Silinmiş'), (4, 'Arşiv')], default=1)),
                ('yayin_zamani', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guncelleme_zamani', models.DateTimeField(blank=True, null=True)),
                ('gorsel_url', models.URLField(blank=True, help_text='Kaynaktaki adres. Yalnız izdir; sayfa uzağa bağlanmaz.', max_length=600)),
                ('gorsel_alt', models.CharField(blank=True, max_length=300)),
                ('gorsel_var', models.BooleanField(default=False, help_text='Yerelde dosya var mı.')),
                ('gorsel_dosya', models.CharField(blank=True, help_text='ARŞİV KÖKÜNE göreli yol, ör. gorseller-galeri/2021-02/x.webp.', max_length=300)),
                ('eski_url', models.URLField(blank=True, max_length=600)),
                ('goc_guveni', models.CharField(blank=True, max_length=12)),
                ('govde', models.TextField(blank=True)),
                ('kelime_sayisi', models.PositiveIntegerField(default=0)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taksonomi.kategori')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tum_yazilari', to='medya.yazar')),
            ],
            options={
                'verbose_name': 'köşe yazısı',
                'verbose_name_plural': 'köşe yazıları',
                'ordering': ['-yayin_zamani'],
            },
        ),
        migrations.AddIndex(
            model_name='fotogaleri',
            index=models.Index(fields=['kategori', '-yayin_zamani'], name='medya_fotog_kategor_815b38_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['kategori', '-yayin_zamani'], name='medya_video_kategor_2b087c_idx'),
        ),
        migrations.AddIndex(
            model_name='koseyazisi',
            index=models.Index(fields=['yazar', '-yayin_zamani'], name='medya_kosey_yazar_i_e3b41f_idx'),
        ),
    ]
