# Generated by Django 5.2.17 on 2026-08-26 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taksonomi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigIntegerField(editable=False, help_text='Eski sistemdeki kimlik. Adresin parçası.', primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, max_length=220)),
                ('baslik', models.CharField(max_length=300)),
                ('spot', models.TextField(blank=True)),
                ('govde', models.TextField(blank=True)),
                ('durum', models.PositiveSmallIntegerField(choices=[(1, 'Aktif'), (2, 'Pasif'), (3, 'Silinmiş'), (4, 'Arşiv')], default=1)),
                ('hazirlik', models.CharField(blank=True, choices=[('taslak', 'Taslak'), ('incelemede', 'İncelemede'), ('hazir', 'Yayına hazır')], max_length=12)),
                ('yayin_zamani', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guncelleme_zamani', models.DateTimeField(blank=True, null=True)),
                ('gorsel_url', models.URLField(blank=True, help_text='Uzak adres. 2023-07 öncesinde dosya SUNUCUDA YOK.', max_length=600)),
                ('gorsel_alt', models.CharField(blank=True, max_length=300)),
                ('gorsel_var', models.BooleanField(default=False, help_text='Yerelde dosya var mı.')),
                ('kelime_sayisi', models.PositiveIntegerField(default=0)),
                ('eski_url', models.URLField(blank=True, max_length=600)),
                ('goc_guveni', models.CharField(blank=True, max_length=12)),
                ('ilce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haberler', to='taksonomi.ilce')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='haberler', to='taksonomi.kategori')),
                ('kaynaklar', models.ManyToManyField(blank=True, related_name='haberler', to='taksonomi.kaynak')),
            ],
            options={
                'verbose_name': 'haber',
                'verbose_name_plural': 'haberler',
                'ordering': ['-yayin_zamani'],
                'indexes': [models.Index(fields=['kategori', '-yayin_zamani'], name='icerik_habe_kategor_32060b_idx')],
            },
        ),
    ]
