# Generated by Django 5.2.17 on 2026-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='gorsel_dosya',
            field=models.CharField(blank=True, help_text='Arşiv köküne göreli yol, ör. gorseller/2026-01/dosya.webp. Sayfa bunu kullanır; gorsel_url yalnız izdir.', max_length=300),
        ),
    ]
