# Generated by Django 5.2.17 on 2026-08-26 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0002_haber_gorsel_dosya'),
        ('taksonomi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='etiketler',
            field=models.ManyToManyField(blank=True, related_name='haberler', to='taksonomi.etiket'),
        ),
        migrations.AddField(
            model_name='haber',
            name='gomulu_kod',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='haber',
            name='ikinci_baslik',
            field=models.CharField(blank=True, help_text='Panelde varsayılan kapalı, açılır alan.', max_length=300),
        ),
        migrations.AddField(
            model_name='haber',
            name='ilgili_haberler',
            field=models.ManyToManyField(blank=True, related_name='ilgili_olduklari', to='icerik.haber'),
        ),
        migrations.AddField(
            model_name='haber',
            name='kaynak_turu',
            field=models.CharField(choices=[('ajans', 'Ajans'), ('dis_yayin', 'Dış yayın'), ('muhabir', 'Kendi muhabirimiz')], default='ajans', max_length=12),
        ),
        migrations.AddField(
            model_name='haber',
            name='manset_ana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='haber',
            name='manset_kare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='haber',
            name='manset_tepe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='haber',
            name='meta_yazar',
            field=models.CharField(blank=True, choices=[('fikir_iscisi', 'Fikir İşçisi'), ('bulten', 'Bülten'), ('haber_ajansi', 'Haber Ajansı'), ('haber_merkezi', 'Haber Merkezi'), ('icerik_aktarimi', 'İçerik Aktarımı'), ('alinti', 'Alıntı/İktibas')], help_text='Yasal sonuç doğurur. Kaynak türünden türetilir; elle değiştirilirse türetim durur.', max_length=20),
        ),
        migrations.AddField(
            model_name='haber',
            name='meta_yazar_elle',
            field=models.BooleanField(default=False, help_text='Editör meta yazar değerini elle seçtiyse doğru; türetim artık ezmez.'),
        ),
        migrations.AddField(
            model_name='haber',
            name='muhabir',
            field=models.CharField(blank=True, help_text="Kaynak türü 'Kendi muhabirimiz' ise doldurulur.", max_length=120),
        ),
        migrations.AddField(
            model_name='haber',
            name='odak_kelime',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='haber',
            name='olusturan',
            field=models.ForeignKey(blank=True, help_text="Haberi giren kullanıcı. 'Kendi haberini yayınlama' yetkisi buna bakar.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haberleri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='haber',
            name='rss',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='haber',
            name='seo_baslik',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='haber',
            name='yonlendirme_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='haber',
            name='yorumlar_acik',
            field=models.BooleanField(default=True),
        ),
    ]
