# Generated by Django 5.2.17 on 2026-08-26 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0003_haber_etiketler_haber_gomulu_kod_haber_ikinci_baslik_and_more'),
        ('taksonomi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haber',
            options={'ordering': ['-yayin_zamani'], 'permissions': [('haber_girme', 'Haber girme (taslak)'), ('kendi_haberini_yayinlama', 'Kendi haberini yayınlama'), ('baskasinin_haberini_yayinlama', 'Başkasının haberini yayınlama'), ('haberi_arsivleme', 'Haberi arşive alma'), ('mansete_alma', 'Manşete alma'), ('sayfa_duzeni', 'Sayfa düzeni ve reklam alanları'), ('resmi_ilan_girme', 'Resmî ilan girme'), ('reklam_kampanyasi', 'Reklam kampanyası'), ('yorum_onaylama', 'Yorum onaylama'), ('kose_yonetimi', 'Köşe yazısı ve yazar yönetimi'), ('konu_yonetimi', 'Konu açma ve bağlama'), ('taksonomi_duzenleme', 'Taksonomi düzenleme'), ('kullanici_yonetimi', 'Kullanıcı ve rol yönetimi'), ('log_goruntuleme', 'Log kayıtları')], 'verbose_name': 'haber', 'verbose_name_plural': 'haberler'},
        ),
        migrations.AddIndex(
            model_name='haber',
            index=models.Index(fields=['durum', 'hazirlik'], name='icerik_habe_durum_8a0e62_idx'),
        ),
    ]
