# Generated by Django 5.2.17 on 2026-08-28 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0004_alter_haber_options_and_more'),
        ('taksonomi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik_turu', models.CharField(choices=[('haber', 'Haber'), ('kose', 'Köşe yazısı'), ('galeri', 'Foto galeri'), ('video', 'Video')], default='haber', max_length=8)),
                ('icerik_id', models.BigIntegerField(blank=True, help_text='§13: haber seçilmeden gönderim yapılamaz.', null=True)),
                ('baslik', models.CharField(max_length=50)),
                ('gonderim_zamani', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('hedef_sayisi', models.PositiveIntegerField(default=0)),
                ('acan_sayisi', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'bildirim',
                'verbose_name_plural': 'bildirimler',
                'ordering': ['-gonderim_zamani', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Gazete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, unique=True)),
                ('bik_kodu', models.CharField(blank=True, max_length=20)),
                ('sira', models.PositiveSmallIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
                ('bizim_mi', models.BooleanField(default=False, help_text="Bursa Hakimiyet'in kendi kaydı; ayrı işaretlenir.")),
            ],
            options={
                'verbose_name': 'gazete',
                'verbose_name_plural': 'gazeteler',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='IkiAdimli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yontem', models.CharField(choices=[('authenticator', 'Google Authenticator'), ('sms', 'SMS')], default='authenticator', max_length=16)),
                ('gizli_anahtar', models.CharField(blank=True, help_text='ŞİFRELEME KARARI BEKLİYOR — bu alana yazan bir akış bilerek kurulmadı (§24.10).', max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('dogrulandi_mi', models.BooleanField(default=False)),
                ('son_kullanim', models.DateTimeField(blank=True, null=True)),
                ('yedek_kodlar', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'iki adımlı doğrulama',
                'verbose_name_plural': 'iki adımlı doğrulamalar',
            },
        ),
        migrations.CreateModel(
            name='LogKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiil', models.CharField(choices=[('giris', 'Oturum açma'), ('giris_basarisiz', 'Başarısız oturum denemesi'), ('cikis', 'Oturum kapatma'), ('yayina_alma', 'Yayına alma'), ('yayindan_cekme', 'Yayından çekme'), ('arsivleme', 'Arşive alma'), ('mansete_alma', 'Manşete alma'), ('mansetten_cikarma', 'Manşetten çıkarma'), ('kategori_degistirme', 'Kategori değiştirme'), ('toplu_islem', 'Toplu işlem'), ('kaynak_birlestirme', 'Kaynak birleştirme'), ('yorum_duzenleme', 'Yorum düzenleme'), ('yorum_karari', 'Yorum onaylama/reddetme'), ('kullanici_degisikligi', 'Kullanıcı veya rol değişikliği'), ('parola_degisikligi', 'Parola değişikliği'), ('resmi_ilan', 'Resmî ilan girme/silme')], max_length=32)),
                ('hedef_tur', models.CharField(blank=True, help_text='Neyin değiştiği. Bu alan olmadan kayıt işe yaramaz.', max_length=24)),
                ('hedef_id', models.BigIntegerField(blank=True, null=True)),
                ('zaman', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('oncesi', models.JSONField(blank=True, null=True)),
                ('sonrasi', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('tarayici', models.CharField(blank=True, max_length=300)),
                ('toplu_islem_kimligi', models.CharField(blank=True, help_text='Aynı toplu fiilin kayıtlarını birbirine bağlar.', max_length=36)),
                ('gerekce', models.CharField(blank=True, max_length=200)),
                ('etkilenen_sayisi', models.PositiveIntegerField(default=1, help_text='Toplu işlemde kaç kayıt etkilendi.')),
            ],
            options={
                'verbose_name': 'log kaydı',
                'verbose_name_plural': 'log kayıtları',
                'ordering': ['-zaman'],
            },
        ),
        migrations.CreateModel(
            name='ReklamKampanyasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('gorsel_dosya', models.CharField(blank=True, max_length=300)),
                ('gorsel_alt', models.CharField(blank=True, max_length=300)),
                ('hedef_adres', models.URLField(blank=True, max_length=600)),
                ('baslangic', models.DateField(blank=True, null=True)),
                ('bitis', models.DateField(blank=True, null=True)),
                ('durum', models.PositiveSmallIntegerField(choices=[(1, 'Aktif'), (2, 'Pasif')], default=2)),
            ],
            options={
                'verbose_name': 'reklam kampanyası',
                'verbose_name_plural': 'reklam kampanyaları',
                'ordering': ['-baslangic', 'baslik'],
            },
        ),
        migrations.CreateModel(
            name='ReklamYuvasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Şablonun çağırdığı ad. DEĞİŞTİRİLMEMELİ: anasayfa yuvaları bu adla arıyor.', max_length=120, unique=True)),
                ('konum', models.CharField(help_text='Sayfadaki yeri.', max_length=80)),
                ('genislik', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yukseklik', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cihaz', models.CharField(choices=[('hepsi', 'Hepsi'), ('masaustu', 'Masaüstü'), ('mobil', 'Mobil')], default='hepsi', max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('yer_tutucu_mu', models.BooleanField(default=False, help_text='Dökümde 6 kayıt yuva değil, boş yuvanın görünen hâliydi.')),
            ],
            options={
                'verbose_name': 'reklam yuvası',
                'verbose_name_plural': 'reklam yuvaları',
                'ordering': ['konum', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='ResmiIlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=300)),
                ('tur', models.CharField(choices=[('icra', 'İCRA'), ('ihale', 'İHALE'), ('tebligat', 'TEBLİGAT'), ('personel', 'PERSONEL ALIMI')], default='ihale', max_length=10)),
                ('metin', models.TextField(blank=True)),
                ('yayin_tarihi', models.DateField(blank=True, db_index=True, null=True)),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('bik_kodu', models.CharField(blank=True, max_length=40)),
                ('durum', models.PositiveSmallIntegerField(choices=[(1, 'Aktif'), (2, 'Pasif'), (4, 'Arşiv')], default=1)),
            ],
            options={
                'verbose_name': 'resmî ilan',
                'verbose_name_plural': 'resmî ilanlar',
                'ordering': ['-yayin_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SonDakika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('adres', models.CharField(blank=True, help_text='Serbest adres. Boşsa bağlı haberin adresi kullanılır.', max_length=600)),
                ('baslangic', models.DateTimeField(default=django.utils.timezone.now)),
                ('bitis', models.DateTimeField(blank=True, null=True)),
                ('sira', models.PositiveSmallIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'son dakika',
                'verbose_name_plural': 'son dakika kayıtları',
                'ordering': ['sira', '-baslangic'],
            },
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik_turu', models.CharField(choices=[('haber', 'Haber'), ('kose', 'Köşe yazısı'), ('galeri', 'Foto galeri'), ('video', 'Video')], default='haber', max_length=8)),
                ('icerik_id', models.BigIntegerField(help_text='Yorumlanan kaydın kimliği. FK değil: dört aileye bağlanır.')),
                ('okur_adi', models.CharField(max_length=120)),
                ('metin', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('tarih', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('durum', models.PositiveSmallIntegerField(choices=[(1, 'Aktif'), (2, 'Pasif'), (3, 'Silinmiş')], default=2)),
                ('duzenlendi_mi', models.BooleanField(default=False, help_text='Okur, yorumunun değiştirildiğini görebilmeli.')),
                ('duzenleme_gerekcesi', models.CharField(blank=True, help_text='Kişisel veri / hakaret / reklam. Gerekçesiz kaydedilmez.', max_length=200)),
                ('ozgun_metin', models.TextField(blank=True, help_text='Düzenlemeden önceki hâli; iz olarak saklanır.')),
            ],
            options={
                'verbose_name': 'yorum',
                'verbose_name_plural': 'yorumlar',
                'ordering': ['-tarih'],
            },
        ),
        migrations.AddIndex(
            model_name='haber',
            index=models.Index(fields=['ilce', '-yayin_zamani'], name='icerik_habe_ilce_id_72bdcf_idx'),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='gonderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bildirimleri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ikiadimli',
            name='kullanici',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iki_adimli', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logkaydi',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_kayitlari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reklamkampanyasi',
            name='olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reklam_kampanyalari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reklamkampanyasi',
            name='yuva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kampanyalar', to='icerik.reklamyuvasi'),
        ),
        migrations.AddField(
            model_name='resmiilan',
            name='gazete',
            field=models.ForeignKey(blank=True, help_text='Hangi gazetede yayımlandı. Dökümde bu bağ GÖRÜNMÜYOR; isteğe bağlı bırakıldı (§24.5).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilanlar', to='icerik.gazete'),
        ),
        migrations.AddField(
            model_name='resmiilan',
            name='olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resmi_ilanlari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sondakika',
            name='haber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son_dakika_kayitlari', to='icerik.haber'),
        ),
        migrations.AddField(
            model_name='sondakika',
            name='olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son_dakikalari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yorum',
            name='duzenleyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duzenledigi_yorumlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yorum',
            name='onaylayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onayladigi_yorumlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='logkaydi',
            index=models.Index(fields=['hedef_tur', 'hedef_id'], name='icerik_logk_hedef_t_7153dc_idx'),
        ),
        migrations.AddIndex(
            model_name='logkaydi',
            index=models.Index(fields=['kullanici', '-zaman'], name='icerik_logk_kullani_9df2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='logkaydi',
            index=models.Index(fields=['fiil', '-zaman'], name='icerik_logk_fiil_e8975b_idx'),
        ),
        migrations.AddIndex(
            model_name='logkaydi',
            index=models.Index(fields=['toplu_islem_kimligi'], name='icerik_logk_toplu_i_b8bde9_idx'),
        ),
        migrations.AddIndex(
            model_name='reklamkampanyasi',
            index=models.Index(fields=['yuva', 'durum'], name='icerik_rekl_yuva_id_d0e4af_idx'),
        ),
        migrations.AddIndex(
            model_name='resmiilan',
            index=models.Index(fields=['tur', '-yayin_tarihi'], name='icerik_resm_tur_0f9881_idx'),
        ),
        migrations.AddIndex(
            model_name='sondakika',
            index=models.Index(fields=['aktif', 'sira'], name='icerik_sond_aktif_2c9437_idx'),
        ),
        migrations.AddIndex(
            model_name='yorum',
            index=models.Index(fields=['icerik_turu', 'icerik_id'], name='icerik_yoru_icerik__ca2399_idx'),
        ),
        migrations.AddIndex(
            model_name='yorum',
            index=models.Index(fields=['durum', '-tarih'], name='icerik_yoru_durum_f1c92d_idx'),
        ),
        # PAKETIN SONU: istatistikleri tazele.
        #
        # Gerekce olculdu (goc ajani, 28 Agustos 2026): SQLite sema
        # degisikliklerinin cogu tabloyu kopyaliyor ve bu `sqlite_stat1`i
        # bayatlatiyor. Istatistikler 92.666 satir sanirken gercek 356.839'du
        # ve ilce sayfasi tam tarama secip **745 ms** suruyordu; `ANALYZE`
        # sonrasi **26 ms**'ye indi.
        #
        # Bu migration `icerik_haber`e yeni bir indeks ekliyor. Yeni indeksin
        # istatistigi yoksa planlayici onu kullanmayabilir; ANALYZE olmadan
        # ilce sayfasi sessizce eski suresine geri duser ve kimse fark etmez.
        #
        # Geri alma: ANALYZE'in tersi yok, istatistik tablosu birakilir.
        # Zararsiz -- `sqlite_stat1` yalniz planlayiciyi besler.
        migrations.RunSQL(
            sql="ANALYZE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
