# Generated by Django 5.2.17 on 2026-08-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0006_manset_kismi_indeksleri'),
        ('medya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='bagli_galeriler',
            field=models.ManyToManyField(blank=True, help_text='Habere iliştirilen foto galeriler.', related_name='bagli_haberler', to='medya.fotogaleri'),
        ),
    ]
