# Generated by Django 5.2.17 on 2026-08-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0008_kaynak_turu_bos_olabilir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KampanyaYuva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'kampanya-yuva bağı',
                'verbose_name_plural': 'kampanya-yuva bağları',
            },
        ),
        migrations.RemoveIndex(
            model_name='reklamkampanyasi',
            name='icerik_rekl_yuva_id_d0e4af_idx',
        ),
        migrations.RemoveField(
            model_name='reklamkampanyasi',
            name='yuva',
        ),
        migrations.AddField(
            model_name='kampanyayuva',
            name='kampanya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icerik.reklamkampanyasi'),
        ),
        migrations.AddField(
            model_name='kampanyayuva',
            name='yuva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='icerik.reklamyuvasi'),
        ),
        migrations.AddField(
            model_name='reklamkampanyasi',
            name='yuvalar',
            field=models.ManyToManyField(help_text='Bir kampanya birden çok yuvada yayımlanabilir.', related_name='kampanyalar', through='icerik.KampanyaYuva', to='icerik.reklamyuvasi'),
        ),
        migrations.AddIndex(
            model_name='reklamkampanyasi',
            index=models.Index(fields=['durum'], name='icerik_rekl_durum_6723ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='kampanyayuva',
            constraint=models.UniqueConstraint(fields=('kampanya', 'yuva'), name='kampanya_yuva_tek'),
        ),
    ]
