# Generated by Django 5.2.17 on 2026-08-29 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0009_kampanya_coka_cok_yuva'),
        ('medya', '0001_initial'),
        ('taksonomi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='haber',
            index=models.Index(fields=['kategori', 'durum'], name='icerik_habe_kategor_d7bb73_idx'),
        ),
        migrations.AddIndex(
            model_name='haber',
            index=models.Index(fields=['olusturan', 'durum'], name='icerik_habe_olustur_eca571_idx'),
        ),
    ]
