"""
Django settings for cekirdek project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Gizli anahtar, hata ayiklama ve izinli sunucu adlari ortamdan okunur.
# Gelistirmede varsayilanlar isler; yayinda BH_GIZLI_ANAHTAR ve BH_HATA_AYIKLA
# ortam degiskenleri verilmek zorundadir (F8 kesim listesi).
SECRET_KEY = os.environ.get(
    "BH_GIZLI_ANAHTAR",
    "django-insecure-9v%)%ub9qz=p(%nc&d7f=&0^9c!l34av2r-)22@c4cn7i@bzfa")

DEBUG = os.environ.get("BH_HATA_AYIKLA", "1") == "1"

ALLOWED_HOSTS = [a for a in os.environ.get(
    "BH_SUNUCU_ADLARI", "127.0.0.1,localhost").split(",") if a]


# Application definition

INSTALLED_APPS = [
    "taksonomi",
    "icerik",
    "medya",
    "besleme",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cekirdek.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # APP_DIRS yukleyicisi sabit "templates" adini arar; sablonlar
        # "sablonlar" altinda oldugu icin yollar elle veriliyor.
        'DIRS': [BASE_DIR / "sablonlar", BASE_DIR / "medya" / "sablonlar"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'icerik.baglam.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'cekirdek.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "tr"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Arsiv gorselleri depo icinde degil: tarama D: surucusune yaziyor ve
# 92.666 kayitlik veri repoya girmez. Sayfa bu kokten servis eder.
ARSIV_KOK = Path(os.environ.get("BH_ARSIV_KOK", "D:/bursa-hakimiyet-arsiv"))
ARSIV_GORSEL_KOK = ARSIV_KOK / "gorseller"
ARSIV_GORSEL_URL = "/arsiv-gorsel/"

# Canli veri betiklerinin ciktisi (canli-veri/veri/). Site yalniz OKUR;
# cekme isi zamanlanmis gorevde, siteden bagimsiz.
CANLI_VERI_KOK = Path(os.environ.get(
    "BH_CANLI_VERI_KOK", BASE_DIR.parent / "canli-veri" / "veri"))

STATIC_URL = "statik/"

# Sitenin kendi varliklari uygulama icinde; demo fotograflari depo kokundeki
# gorseller/ klasorunde duruyor ve oradan servis ediliyor - kopyalanmiyor.
STATICFILES_DIRS = [
    BASE_DIR / "statik",
    ("gorseller", BASE_DIR.parent / "gorseller"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Canli adreslerde sondaki egik cizgi YOK; Django yonlendirmesin.
APPEND_SLASH = False

# Panel giris/cikis adresleri.
# Besleme (sitemap/RSS) mutlak adres uretir.
SITE_KOKU = os.environ.get("BH_SITE_KOKU", "https://www.bursahakimiyet.com.tr")

# --- reklam demo agi (31 Agustos 2026, kullanici karari) -----------------
#
# Google Ad Manager'in ACIK demo agi; hesap ve anahtar gerektirmez. Amaci
# yuvalarin gercek bir reklamla nasil durdugunu gormek — gelir sunumu DEGIL.
# Gercek sunum F7(b)'nin isi ve kendi kararlarini (yuva modelinden render,
# kampanya eslesmesi, ads.txt) ayrica ister.
#
# VARSAYILAN KAPALI ve bu bilincli. GPT dis bir betiktir
# (securepubads.g.doubleclick.net), ucuncu taraf cerezi birakir ve canlida
# KVKK tarafinda cerez aydinlatmasi gerektirir. Site su an disaridan yalniz
# Google Fonts cekiyor; bayrak kapaliyken bu duzen bozulmaz ve sayfa
# internetsiz de aynen acilir.
REKLAM_DEMO = os.environ.get("BH_REKLAM_DEMO", "0") == "1"

# Olculdu (31 Agustos 2026, bassiz Chrome, canli demo agina karsi): bu yol
# 300x250, 160x600 ve 728x90 doldurur; 970x250, 300x600 ve 320x100 BOS
# doner. Ust seridin cok olculu tanimi (970x250 + 728x90) bu yuzden var.
REKLAM_DEMO_YOLU = os.environ.get(
    "BH_REKLAM_YOLU", "/6355419/Travel/Europe/France/Paris")

LOGIN_URL = "/panel/giris"
LOGIN_REDIRECT_URL = "/panel/"
LOGOUT_REDIRECT_URL = "/panel/giris"
